CREATE TABLE IF NOT EXISTS phrases (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    text VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    nationality VARCHAR(255)
);

INSERT INTO phrases (text, author, nationality) VALUES
('La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'John Lennon', 'Británico'),
('El único modo de hacer un gran trabajo es amar lo que haces.', 'Steve Jobs', 'Estadounidense'),
('El mayor riesgo es no tomar ninguno.', 'Mark Zuckerberg', 'Estadounidense'),
('La vida es un 10% lo que nos pasa y un 90% cómo reaccionamos a ello.', 'Charles R. Swindoll', 'Estadounidense'),
('El propósito de nuestras vidas es ser felices.', 'Dalai Lama', 'Tibetano'),
('La felicidad no es algo hecho. Proviene de tus propias acciones.', 'Dalai Lama', 'Tibetano'),
('La imaginación es más importante que el conocimiento.', 'Albert Einstein', 'Alemán'),
('No hay nada permanente excepto el cambio.', 'Heráclito', 'Griego'),
('Lo que no nos mata nos hace más fuertes.', 'Friedrich Nietzsche', 'Alemán'),
('El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'Robert Collier', 'Estadounidense'),
('Cree que puedes y ya estás a mitad de camino.', 'Theodore Roosevelt', 'Estadounidense'),
('Actúa como si lo que haces marca la diferencia. Lo hace.', 'William James', 'Estadounidense'),
('Nunca es demasiado tarde para ser lo que podrías haber sido.', 'George Eliot', 'Británica'),
('La mejor manera de predecir el futuro es inventarlo.', 'Alan Kay', 'Estadounidense'),
('El tiempo es la cosa más valiosa que una persona puede gastar.', 'Theophrastus', 'Griego'),
('El único lugar donde el éxito viene antes del trabajo es en el diccionario.', 'Vidal Sassoon', 'Británico'),
('No juzgues cada día por la cosecha que recoges, sino por las semillas que plantas.', 'Robert Louis Stevenson', 'Escocés'),
('El viaje de mil millas comienza con un solo paso.', 'Lao Tzu', 'Chino'),
('No se puede nadar hacia nuevos horizontes hasta tener el coraje de perder de vista la orilla.', 'William Faulkner', 'Estadounidense'),
('Si puedes soñarlo, puedes hacerlo.', 'Walt Disney', 'Estadounidense'),
('La mejor venganza es el éxito masivo.', 'Frank Sinatra', 'Estadounidense'),
('No se puede cambiar el pasado, pero se puede aprender de él.', 'Pauline Hill', 'Estadounidense'),
('La vida es corta, haz que cada día cuente.', 'Hugh Hefner', 'Estadounidense'),
('No es lo que miras lo que importa, es lo que ves.', 'Henry David Thoreau', 'Estadounidense'),
('La única manera de hacer un gran trabajo es amar lo que haces.', 'Steve Jobs', 'Estadounidense'),
('No encuentres la falta, encuentra el remedio.', 'Henry Ford', 'Estadounidense'),
('El éxito no es el final, el fracaso no es fatal: lo que cuenta es el valor para continuar.', 'Winston Churchill', 'Británico'),
('La vida es una aventura, atrévete.', 'Teresa de Calcuta', 'Albanesa'),
('La mejor preparación para mañana es dar lo mejor de ti hoy.', 'H. Jackson Brown, Jr.', 'Estadounidense'),
('No cuentes los días, haz que los días cuenten.', 'Muhammad Ali', 'Estadounidense'),
('No importa qué tan lento vayas, siempre y cuando no te detengas.', 'Confucio', 'Chino'),
('La calidad nunca es un accidente, siempre es el resultado de un esfuerzo de la inteligencia.', 'John Ruskin', 'Británico'),
('El fracaso es simplemente la oportunidad para comenzar de nuevo, esta vez de manera más inteligente.', 'Henry Ford', 'Estadounidense'),
('El futuro pertenece a aquellos que creen en la belleza de sus sueños.', 'Eleanor Roosevelt', 'Estadounidense'),
('El amor no se trata de posesión, se trata de aprecio.', 'Osho', 'Indio'),
('La vida es realmente simple, pero insistimos en hacerla complicada.', 'Confucio', 'Chino'),
('La vida no se mide por el número de respiraciones que tomamos, sino por los momentos que nos quitan el aliento.', 'Maya Angelou', 'Estadounidense'),
('El hombre es mortal por sus temores e inmortal por sus deseos.', 'Pitágoras', 'Griego'),
('La paciencia es amarga, pero su fruto es dulce.', 'Jean-Jacques Rousseau', 'Francés'),
('El secreto de la felicidad no es hacer siempre lo que se quiere, sino querer siempre lo que se hace.', 'León Tolstói', 'Ruso'),
('El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'Robert Collier', 'Estadounidense'),
('Si puedes soñarlo, puedes hacerlo.', 'Walt Disney', 'Estadounidense'),
('No juzgues cada día por la cosecha que recoges, sino por las semillas que plantas.', 'Robert Louis Stevenson', 'Escocés'),
('El viaje de mil millas comienza con un solo paso.', 'Lao Tzu', 'Chino'),
('La vida es 10% lo que te sucede y 90% cómo reaccionas ante ello.', 'Charles R. Swindoll', 'Estadounidense'),
('El propósito de nuestras vidas es ser felices.', 'Dalai Lama', 'Tibetano'),
('La felicidad no es algo hecho. Proviene de tus propias acciones.', 'Dalai Lama', 'Tibetano'),
('La imaginación es más importante que el conocimiento.', 'Albert Einstein', 'Alemán'),
('No hay nada permanente excepto el cambio.', 'Heráclito', 'Griego'),
('Lo que no nos mata nos hace más fuertes.', 'Friedrich Nietzsche', 'Alemán'),
('El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'Robert Collier', 'Estadounidense'),
('Cree que puedes y ya estás a mitad de camino.', 'Theodore Roosevelt', 'Estadounidense'),
('Actúa como si lo que haces marca la diferencia. Lo hace.', 'William James', 'Estadounidense'),
('Nunca es demasiado tarde para ser lo que podrías haber sido.', 'George Eliot', 'Británica'),
('La mejor manera de predecir el futuro es inventarlo.', 'Alan Kay', 'Estadounidense'),
('El tiempo es la cosa más valiosa que una persona puede gastar.', 'Theophrastus', 'Griego'),
('El único lugar donde el éxito viene antes del trabajo es en el diccionario.', 'Vidal Sassoon', 'Británico'),
('No juzgues cada día por la cosecha que recoges, sino por las semillas que plantas.', 'Robert Louis Stevenson', 'Escocés'),
('El viaje de mil millas comienza con un solo paso.', 'Lao Tzu', 'Chino'),
('No se puede nadar hacia nuevos horizontes hasta tener el coraje de perder de vista la orilla.', 'William Faulkner', 'Estadounidense'),
('Si puedes soñarlo, puedes hacerlo.', 'Walt Disney', 'Estadounidense'),
('El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'Robert Collier', 'Estadounidense'),
('Cree que puedes y ya estás a mitad de camino.', 'Theodore Roosevelt', 'Estadounidense'),
('Actúa como si lo que haces marca la diferencia. Lo hace.', 'William James', 'Estadounidense'),
('Nunca es demasiado tarde para ser lo que podrías haber sido.', 'George Eliot', 'Británica'),
('La mejor manera de predecir el futuro es inventarlo.', 'Alan Kay', 'Estadounidense'),
('El tiempo es la cosa más valiosa que una persona puede gastar.', 'Theophrastus', 'Griego'),
('El único lugar donde el éxito viene antes del trabajo es en el diccionario.', 'Vidal Sassoon', 'Británico'),
('No juzgues cada día por la cosecha que recoges, sino por las semillas que plantas.', 'Robert Louis Stevenson', 'Escocés'),
('El viaje de mil millas comienza con un solo paso.', 'Lao Tzu', 'Chino'),
('No se puede nadar hacia nuevos horizontes hasta tener el coraje de perder de vista la orilla.', 'William Faulkner', 'Estadounidense'),
('Si puedes soñarlo, puedes hacerlo.', 'Walt Disney', 'Estadounidense'),
('La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.', 'John Lennon', 'Británico'),
('El único modo de hacer un gran trabajo es amar lo que haces.', 'Steve Jobs', 'Estadounidense'),
('El mayor riesgo es no tomar ninguno.', 'Mark Zuckerberg', 'Estadounidense'),
('La vida es un 10% lo que nos pasa y un 90% cómo reaccionamos a ello.', 'Charles R. Swindoll', 'Estadounidense'),
('El propósito de nuestras vidas es ser felices.', 'Dalai Lama', 'Tibetano'),
('La felicidad no es algo hecho. Proviene de tus propias acciones.', 'Dalai Lama', 'Tibetano'),
('La imaginación es más importante que el conocimiento.', 'Albert Einstein', 'Alemán'),
('No hay nada permanente excepto el cambio.', 'Heráclito', 'Griego'),
('Lo que no nos mata nos hace más fuertes.', 'Friedrich Nietzsche', 'Alemán'),
('El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'Robert Collier', 'Estadounidense'),
('Cree que puedes y ya estás a mitad de camino.', 'Theodore Roosevelt', 'Estadounidense'),
('Actúa como si lo que haces marca la diferencia. Lo hace.', 'William James', 'Estadounidense'),
('Nunca es demasiado tarde para ser lo que podrías haber sido.', 'George Eliot', 'Británica'),
('La mejor manera de predecir el futuro es inventarlo.', 'Alan Kay', 'Estadounidense'),
('El tiempo es la cosa más valiosa que una persona puede gastar.', 'Theophrastus', 'Griego'),
('El único lugar donde el éxito viene antes del trabajo es en el diccionario.', 'Vidal Sassoon', 'Británico'),
('No juzgues cada día por la cosecha que recoges, sino por las semillas que plantas.', 'Robert Louis Stevenson', 'Escocés'),
('El viaje de mil millas comienza con un solo paso.', 'Lao Tzu', 'Chino'),
('No se puede nadar hacia nuevos horizontes hasta tener el coraje de perder de vista la orilla.', 'William Faulkner', 'Estadounidense'),
('Si puedes soñarlo, puedes hacerlo.', 'Walt Disney', 'Estadounidense');
